[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "ctg-wave"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "fenics-dolfinx",
    "matplotlib"
]

[tool.hatch.build.targets.wheel]
packages = ["src/ctg"]
